TRAINING_TRIALS: 2
TRAINING_LEVEL: 3
START_LEVEL: 5
MAX_REVS: 3
MAX_TRIALS: 10
MIN_LEVEL: 2
MAX_LEVEL: 6

# time in seconds
CONST_TIME: 2
LEVEL_TIME: 4
JITTER_TIME: 1

# visual parameters
TEXT_SIZE: 32
FIG_OFFSET: 100
MATRIX_OFFSET: 200

MAIN_FIG_SIZE: 40
MAIN_MOVE_Y: 100

ANSWERS_FIG_SIZE: 40
ANSWERS_MOVE_Y: -100

ARROW_LONG: 10
ARROW_WIDTH: 10
ARROW_COLOR: 'black'

# clock
## show clock n second before trial end
SHOW_CLOCK: 3
CLOCK_POS: [600, 400]
CLOCK_SIZE: 50