TRAINING_TRIALS: [{level: 1, n_trails: 1}, {level: 2, n_trails: 2}, {level: 3, n_trails: 1}]
START_LEVEL: 2
MAX_REVS: 5
MAX_TRIALS: 60
MIN_LEVEL: 1
MAX_LEVEL: 6

# time in seconds
CONST_TIME: 6
LEVEL_TIME: 4
JITTER_TIME: 1.5

# visual parameters
TEXT_SIZE: 32
FIG_OFFSET: 80
MATRIX_OFFSET: 220

MAIN_FIG_SIZE: 40
MAIN_MOVE_Y: 100

ANSWERS_FIG_SIZE: 40
ANSWERS_MOVE_Y: -90

ARROW_LONG: 6
ARROW_WIDTH: 10
ARROW_COLOR: 'black'

# clock
## show clock n second before trial end
SHOW_CLOCK: 4
CLOCK_POS: [0, 350]
CLOCK_SIZE: 120
