TRAINING_TRIALS: [{level: 1, n_trails: 3}, {level: 2, n_trails: 2}, {level: 3, n_trails: 1}]

START_LEVEL: 2
MAX_REVS: 6
MAX_TRIALS: 50
MIN_LEVEL: 1
MAX_LEVEL: 6

# time in seconds
CONST_TIME: 9
LEVEL_TIME: 1.5
JITTER_TIME: 2

# visual parameters
TEXT_SIZE: 32
FIG_OFFSET: 80
MATRIX_OFFSET: 210

MAIN_FIG_SIZE: 50
MAIN_MOVE_Y: 100

ANSWERS_FIG_SIZE: 50
ANSWERS_MOVE_Y: -100

ARROW_LONG: 6
ARROW_WIDTH: 6
ARROW_COLOR: 'black'

# clock
## show clock n second before trial end
SHOW_CLOCK: 3
CLOCK_POS: [0, -270]
CLOCK_SIZE: 150
